apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: master
  name: 10-br-ex-wrk01
spec:
  config:
    ignition:
      version: 3.2.0
    storage:
      files:
      - contents:
          # This source is the Base64 encoded version of the NMState YAML above
          source: data:text/plain;charset=utf-8;base64,<base-64-of-sno-node.yaml>
        mode: 0644
        overwrite: true
        # The path determines which node picks up the config.
        # Use 'cluster.yml' to apply to all nodes in this MachineConfig pool.
        path: /etc/nmstate/openshift/sno-node.yml
